version: "3"

services:
  asr_worker:
    build: worker_asr

    environment:
      QUEUE_SERVER: "localhost:5672"
      FILES_SERVER: "localhost:3001"
      INPUT_QUEUE_NAME: "asr_in"
      OUTPUT_QUEUE_NAME: "asr_out"